# Generated by Django 5.0.1 on 2024-02-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="armour",
            table="armour",
        ),
        migrations.AlterModelTable(
            name="character",
            table="character",
        ),
        migrations.AlterModelTable(
            name="homeworld",
            table="homeworld",
        ),
        migrations.AlterModelTable(
            name="homeworldclass",
            table="homeworld_class",
        ),
    ]
