# Generated by Django 5.0.1 on 2024-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
