# Generated by Django 5.0.1 on 2024-02-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character_builder", "0002_alter_talent_group"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="careerpath",
            table="career_path",
        ),
        migrations.AlterModelTable(
            name="careerrank",
            table="career_rank",
        ),
        migrations.AlterModelTable(
            name="character",
            table="home_world",
        ),
        migrations.AlterModelTable(
            name="divination",
            table="divination",
        ),
        migrations.AlterModelTable(
            name="gear",
            table="gear",
        ),
        migrations.AlterModelTable(
            name="mutation",
            table="mutation",
        ),
        migrations.AlterModelTable(
            name="quirk",
            table="quirk",
        ),
        migrations.AlterModelTable(
            name="skill",
            table="skill",
        ),
        migrations.AlterModelTable(
            name="talent",
            table="talent",
        ),
        migrations.AlterModelTable(
            name="trait",
            table="trait",
        ),
    ]
